### ISSUE TITLE
Improve logic of ParseAnyNumber()

### ISSUE THREAD

**Issue by danielatzirra** [zirra-com/go-utility#12]
https://github.com/zirra-com/go-utility/blob/8eccbe3565c8ba18b2ca51f0bfc1840ce3ef0bde/helper.go#L361

The function currently fails for cases like 1,234,567.78 or 1.234.567,89

**Comment by denisbiryukov** [comment]
Current regular expression:
var reGetDigits = regexp.MustCompile(`^[^\d]*(\d+(?:\.\d*)?)[^\d]*$`)

And ParseAnyNumber(`.123456778`) gives:
123456778.000

It is not very correct I guess.
